const ActionTypes = {
  SET_ORGANISATION_STRUCTURE: "SET_ORGANISATION_STRUCTURE",
  SET_EQUIPMENTS_COUNT_INFO: "SET_EQUIPMENTS_COUNT_INFO",
  SET_AppSnackbar_MESSAGE: "SET_AppSnackbar_MESSAGE"
};

export default ActionTypes;
