const ActionTypes = {
  SET_ORGANISATION_STRUCTURE: "SET_ORGANISATION_STRUCTURE",
  SET_ALL_EQUIPMENT: "SET_ALL_EQUIPMENT",
  SET_LOCAL_EQUIPMENT: "SET_LOCAL_EQUIPMENT",
  SET_APPSNACKBAR_MESSAGE: "SET_APPSNACKBAR_MESSAGE",
  SET_EQUIPMENT_CREATION_IN_PROGRESS: "SET_EQUIPMENT_CREATION_IN_PROGRESS",
  GET_ORGANISATION_STRUCTURE: "GET_ORGANISATION_STRUCTURE",
  GET_ALL_EQUIPMENT: "GET_ALL_EQUIPMENT",
  GET_LOCAL_EQUIPMENT: "GET_LOCAL_EQUIPMENT",
  CREATE_EQUIPMENT: "CREATE_EQUIPMENT",
  UPDATE_EQUIPMENT_COUNT: "UPDATE_EQUIPMENT_COUNT",
  DELETE_EQUIPMENT: "DELETE_EQUIPMENT"
};

export default ActionTypes;
