const ActionTypes = {
  SET_ORGANISATION_STRUCTURE: "SET_ORGANISATION_STRUCTURE",
  SET_EQUIPMENTS_COUNT_INFO: "SET_EQUIPMENTS_COUNT_INFO",
  SET_APPSNACKBAR_MESSAGE: "SET_APPSNACKBAR_MESSAGE"
};

export default ActionTypes;
